spring.application.name=demo

# Database Configuration

spring.datasource.url=jdbc:mysql://db:3306/cicd_db
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

