spring.application.name=demo

# Database Configuration

spring.datasource.url=jdbc:mysql://db:3306/cicd_db
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Email Configuration

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=ishika123@gmail.com
spring.mail.password=fdiy jput gkgb frwq

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
